# Generated by Django 5.1.5 on 2025-02-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='example',
            constraint=models.UniqueConstraint(fields=('text', 'number'), name='unique_text_number'),
        ),
    ]
