# Generated by Django 5.1.5 on 2025-02-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PythonQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('A', models.CharField(max_length=255)),
                ('B', models.CharField(max_length=255)),
                ('C', models.CharField(max_length=255)),
                ('D', models.CharField(max_length=255)),
                ('solution', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
            ],
        ),
    ]
