# Generated by Django 5.1.5 on 2025-02-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonquiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pythonquiz',
            old_name='solution',
            new_name='correct',
        ),
    ]
