# Generated by Django 5.1.5 on 2025-02-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonquiz', '0002_rename_solution_pythonquiz_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('right', models.IntegerField()),
                ('wrong', models.IntegerField()),
            ],
        ),
    ]
